---
name: 🐛 Bug Report
description: Report a bug or issue with the documentation
title: "[BUG]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: e.g., "The link to YouTube analysis is broken"
    validations:
      required: true

  - type: dropdown
    id: affected-area
    attributes:
      label: Affected Area
      description: Which part of the documentation is affected?
      options:
        - Content Accuracy
        - Broken Links
        - Formatting Issues
        - Missing Information
        - Navigation Problems
        - Other
    validations:
      required: true

  - type: dropdown
    id: file-affected
    attributes:
      label: File/Section Affected
      description: Which specific file or section has the issue?
      options:
        - README.md
        - docs/core/brainrot-deep-dive.md
        - docs/core/mental-health-context.md
        - docs/culture/skibidi-toilet.md
        - docs/culture/cultural-references.md
        - docs/platforms/youtube.md
        - docs/platforms/tiktok.md
        - docs/platforms/discord.md
        - Multiple files
        - Not sure
      default: 0
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: e.g., "The link should work and take me to the YouTube analysis"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened
      placeholder: e.g., "The link shows 404 error"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      options:
        - GitHub Web Interface
        - Mobile Browser
        - Desktop Browser
        - Screen Reader
        - Other
      default: 0
    validations:
      required: true

  - type: input
    id: browser-info
    attributes:
      label: Browser/Platform
      description: Which browser or platform are you using?
      placeholder: e.g., "Chrome 120, Windows 11"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here or click to attach
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have checked existing issues for duplicates
          required: true
        - label: I have provided sufficient information for reproduction
          required: true
        - label: This is not a security vulnerability (use private report for that)
          required: true