---
name: 💡 Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: e.g., "It's hard to find specific information in the current documentation"
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Content/Documentation
        - Search Functionality
        - Interactive Features
        - Mobile/Accessibility Improvements
        - Automation/Tools
        - Platform Integration
        - Community Features
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: e.g., "Add a search bar that can search across all documentation files"
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        1. User wants to find information about "rizz"
        2. User types "rizz" in search
        3. User gets results from multiple documents with context
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical - blocks major functionality
        - High - significantly improves experience
        - Medium - nice to have improvement
        - Low - minor enhancement
        - Nice to have - future consideration
      default: 2
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: e.g., "I tried using browser search, but it doesn't search within files"
    validations:
      required: false

  - type: textarea
    id: additional-requirements
    attributes:
      label: Additional Requirements
      description: Any specific requirements or constraints for this feature?
      placeholder: e.g., "Must work on mobile devices, should be fast loading"
    validations:
      required: false

  - type: textarea
    id: mockups-or-examples
    attributes:
      label: Mockups or Examples
      description: If you have mockups, screenshots, or examples, please share them
      placeholder: Drag and drop images or provide links to examples
    validations:
      required: false

  - type: checkboxes
    id: contribution-interest
    attributes:
      label: Contribution Interest
      description: Would you like to help implement this feature?
      options:
        - label: I'm interested in contributing code for this feature
        - label: I'm interested in contributing content for this feature
        - label: I'm interested in testing this feature
        - label: I'm interested in documenting this feature
        - label: I prefer the maintainers to implement this feature
      default: 4

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have checked existing issues for duplicates
          required: true
        - label: I have provided sufficient detail for implementation
          required: true
        - label: This feature aligns with the project goals
          required: true